### ISSUE TITLE
How to restore closed note?

### ISSUE THREAD

**Issue by linsui** [changbowen/DesktopNote#17]
Is there any way to restore a note which is closed but not deleted? Thanks!

**Comment by changbowen** [comment]
I think you will need to replace one of the current notes because I haven't implemented an "open note" function. Exit the application first otherwise it might gets overwritten. Also backup your notes :)
You can see the note file paths in the Options window:
![image](https://user-images.githubusercontent.com/15975872/66730596-61c6f280-ee85-11e9-9559-49601988cf17.png)
The default path of the first note looks like this:
`C:\Users\xxx\Documents\DesktopNoteContent` (the actual content)
`C:\Users\xxx\Documents\DesktopNoteContent.txt` (the text content for backup only)
If more than one note is created the file name will be appended with the current date & time.

**Comment by linsui** [comment]
Thanks, it works. Will there be an "open note" function?

**Comment by changbowen** [comment]
Would be a convenient feature but probably not since I don't really see the need to frequently open notes that was closed previously... Also when you are closing notes you will be prompted for confirmation.
Perhaps you can demonstrate a use case?

**Comment by linsui** [comment]
Sometimes I have several notes but I don't what to show all of them on my desktop. So I want to hide some of them and show them when I need them.

**Comment by changbowen** [comment]
OK so you are a heavy user 😊
Thanks for using it and as always if you are saving important data please remember to back them up.
Adding the button in the right click menu would probably be good enough. I will implement it when I have time. Thank you for the suggestion!

**Comment by linsui** [comment]
Thanks a lot!

**Comment by changbowen** [comment]
210842905f3477a5a183046c1684cd9514a071fc

**Comment by linsui** [comment]
Thanks! It I found a problem. If I close all notes and open notes from tray, it will crash.

**Comment by changbowen** [comment]
I noticed as well. I removed the option to open note from tray in the latest build. OpenFileDialog.ShowDialog() needs a visible window to work otherwise it closes immediately.
You can always create a new window and open notes from there. Not the best logic but... out of ideas

**Comment by linsui** [comment]
How about just quit when all notes is closed?

**Comment by changbowen** [comment]
I think you are right. Check out the latest build.
Also thanks for helping improving the app. Let me know if this issue can be closed.

**Comment by linsui** [comment]
Thanks! It works well for me.
